leftnav:
- identifier: 43de67a8-08a9-4b91-a7f4-9ebc59d29c08
  name: MIT Climate Primer website
  pageRef: /external-resources/mit-climate-primer-website_43de67a8-08a9-4b91-a7f4-9ebc59d29c08
  weight: 1000
